name: Publish Tagged Commit to PyPI

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  build-n-publish:
    name: Build and publish Python Package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: er28-0652/setup-ghidra@master
        with:
          version: "9.2.2"

      - name: Prepare Jython Environment
        run: >-
          mkvirtualenv -p python2.7 ghidra
          jython_site_packages=~/.local/lib/jython2.7/site-packages
          mkdir -p $jython_site_packages
          python2.7 -c "import site; print(site.getusersitepackages()); print(site.getsitepackages()[-1])" > $jython_site_packages/python.pth
          pip2.7 install attrs typing

      - name: Build Package
        run: >-
          "$GHIDRA_INSTALL_DIR/support/analyzeHeadless" /tmp tmp -scriptPath $(pwd) -preScript generate_ghidra_pyi.py ./ ${{ github.ref }}

      - name: Check Package Results # analyzeHeadless doesn't return with a nonzero exit code on script failure
        run: >-
          test -f setup.py
          test -d ghidra-stubs


      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

# TODO: Setup publishing to PyPI by creating package and token and adding to GitHub secrets
#      - name: Publish distribution 📦 to PyPI
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}


      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
